### ISSUE TITLE
GTA 5 Cheats

### ISSUE THREAD

**Issue by zain-masood** [teambition/gta#10]
All Gta 5 Cheats 100% Working New Codes 2016 Version.
<a href="http://hackingevent.com/grand-theft-auto-gta-san-andreas-cheats-codes-for-ps3/">GTA San Andreas Cheats Ps2</a>
<a href="http://hackingevent.com/gta-5-cheats-codes-ps3-grand-theft-auto-v-secrets/">GTA 5 Cheats Ps3</a>
<a href="http://hackingevent.com/category/games-cheats/gta-5-cheats-codes-and-secrets/">GTA 5 Cheat Codes</a>

**Comment by meowlab** [comment]
Locked as off-topic
